name: Custom Product pipeline

on:
  workflow_dispatch:
    inputs:
      suiteName:
        description: "Please specify suite: SmokeSuite, LoginSuite, ProductSuite, RegressionSuite"
        required: true
        type: choice
        options:
          - SmokeSuite
          - RegressionSuite
          - LoginSuite
          - ProductSuite
        default: SmokeSuite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
            
            # INSTALARE CHROME (CRITIC)
                   - name: Setup Chrome
                   uses: browser-actions/setup-chrome@v1

      - name: Run automation tests
        run: mvn clean install -Dgroups=${{github.event.inputs.suiteName}}
